projects:
  mysite-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: ap-northeast-1
        apiId: rynyvat3hzalbibyga76md5b4i
        maxDepth: 2
extensions:
  amplify:
    version: 3
